name: Check
on: [push, pull_request]
jobs:
  check:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v2
        with:
          configuration: tests/phpunit.xml
          args: --coverage-text